### PR TITLE
Solutions Page

### PR DESCRIPTION
**Pull request by marinicf**

### CODE REVIEW

**Comment by Fudge-Lickels** [comment]
Absolutely love the page. Would it be possible to make the contact us
button take the user to the Contact the development team part of the
contact us page?
If fine if it isn't possible. I still love the work. Please don't forget to
pull the changes from the main before you merge.

**Review by Fudge-Lickels — APPROVED** [review]
Absolutely love the page. Would it be possible to make the contact us button take the user to the Contact the development team part of the contact us page?
If fine if it isn't possible. I still love the work. Please don't forget to pull the changes from the main before you merge.

**Comment by marinicf** [comment]
Yes I found solution bit it's requires small changes to contact.html
The section you want to scroll to must have an id e.g.

<section id="contactScroll" class="developer-contact">
.
.
.
</section>

then button in my page can look something like this

<a class="contactBtn" href="./contact.html#contactScroll">Contact us</a>

**Comment by Fudge-Lickels** [comment]
The id has been added

**Review by NeNorvalls — APPROVED** [review]

**Pull request closed without merging**
